-- Rentbox.ee Booking + Calendar System (PostgreSQL)
-- Migration 001: core schema + hard overlap protection + audit + ICS tokens
--
-- Assumptions:
-- - All timestamps are timestamptz in DB (UTC internally)
-- - UI renders in locker timezone (default Europe/Tallinn)
-- - Money is stored as integer minor units (e.g. cents)

BEGIN;

-- Required for exclusion constraints (btree types in GiST)
CREATE EXTENSION IF NOT EXISTS btree_gist;
-- Optional: token generation / hashing helpers (gen_random_uuid)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================
-- Catalog / inventory
-- =========================================
CREATE TABLE IF NOT EXISTS products (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          TEXT NOT NULL UNIQUE,
  name          TEXT NOT NULL,
  price_hour    INT  NOT NULL CHECK (price_hour >= 0),
  price_day     INT  NOT NULL CHECK (price_day >= 0),
  deposit       INT  NOT NULL CHECK (deposit >= 0),
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lockers (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  address       TEXT NOT NULL,
  lat           DOUBLE PRECISION,
  lng           DOUBLE PRECISION,
  timezone      TEXT NOT NULL DEFAULT 'Europe/Tallinn',
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS compartments (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  locker_id     BIGINT NOT NULL REFERENCES lockers(id) ON DELETE RESTRICT,
  code          TEXT NOT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (locker_id, code)
);

CREATE TABLE IF NOT EXISTS compartment_products (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  compartment_id  BIGINT NOT NULL REFERENCES compartments(id) ON DELETE RESTRICT,
  product_id      BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (compartment_id, product_id)
);

CREATE INDEX IF NOT EXISTS compartment_products_product_id_idx
  ON compartment_products(product_id)
  WHERE is_active;

-- =========================================
-- Booking (time-based, compartment-bound)
-- =========================================
CREATE TABLE IF NOT EXISTS bookings (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id        BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  compartment_id    BIGINT NOT NULL REFERENCES compartments(id) ON DELETE RESTRICT,
  user_id           UUID NULL,
  start_at          TIMESTAMPTZ NOT NULL,
  end_at            TIMESTAMPTZ NOT NULL,
  status            TEXT NOT NULL,
  total_price       INT  NOT NULL CHECK (total_price >= 0),
  deposit           INT  NOT NULL CHECK (deposit >= 0),
  pending_expires_at TIMESTAMPTZ NULL,
  idempotency_key   TEXT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT bookings_time_valid CHECK (start_at < end_at),
  CONSTRAINT bookings_status_valid CHECK (
    status IN ('pending','paid','active','completed','overdue','cancelled','expired')
  )
);

-- Helpful read-path indexes
CREATE INDEX IF NOT EXISTS bookings_compartment_time_idx
  ON bookings(compartment_id, start_at, end_at);
CREATE INDEX IF NOT EXISTS bookings_product_time_idx
  ON bookings(product_id, start_at, end_at);
CREATE INDEX IF NOT EXISTS bookings_status_idx
  ON bookings(status);
CREATE UNIQUE INDEX IF NOT EXISTS bookings_idempotency_key_uniq
  ON bookings(idempotency_key)
  WHERE idempotency_key IS NOT NULL;

-- Hard protection: no overlapping bookings per compartment for blocking statuses
-- Overlap uses half-open range: [start_at, end_at)
ALTER TABLE bookings
  ADD CONSTRAINT bookings_no_overlap_blocking
  EXCLUDE USING gist (
    compartment_id WITH =,
    tstzrange(start_at, end_at, '[)') WITH &&
  )
  WHERE (status IN ('pending','paid','active'));

-- =========================================
-- Calendar events (bookings + maintenance + blocks)
-- =========================================
CREATE TABLE IF NOT EXISTS calendar_events (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope           TEXT NOT NULL, -- 'booking' | 'maintenance' | 'block'
  booking_id      BIGINT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  locker_id       BIGINT NULL REFERENCES lockers(id) ON DELETE CASCADE,
  compartment_id  BIGINT NULL REFERENCES compartments(id) ON DELETE CASCADE,
  title           TEXT NOT NULL,
  start_at        TIMESTAMPTZ NOT NULL,
  end_at          TIMESTAMPTZ NOT NULL,
  status          TEXT NOT NULL DEFAULT 'active',
  meta            JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT calendar_events_time_valid CHECK (start_at < end_at),
  CONSTRAINT calendar_events_scope_valid CHECK (scope IN ('booking','maintenance','block'))
);

CREATE INDEX IF NOT EXISTS calendar_events_compartment_time_idx
  ON calendar_events(compartment_id, start_at, end_at)
  WHERE compartment_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS calendar_events_locker_time_idx
  ON calendar_events(locker_id, start_at, end_at)
  WHERE locker_id IS NOT NULL;

-- =========================================
-- Audit log (status changes + admin blocks)
-- =========================================
CREATE TABLE IF NOT EXISTS booking_audit_log (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id    BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  from_status   TEXT NULL,
  to_status     TEXT NOT NULL,
  actor_type    TEXT NOT NULL DEFAULT 'system', -- 'user'|'admin'|'system'
  actor_id      UUID NULL,
  reason        TEXT NULL,
  meta          JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT booking_audit_actor_type_valid CHECK (actor_type IN ('user','admin','system')),
  CONSTRAINT booking_audit_to_status_valid CHECK (
    to_status IN ('pending','paid','active','completed','overdue','cancelled','expired')
  )
);

CREATE INDEX IF NOT EXISTS booking_audit_log_booking_id_created_at_idx
  ON booking_audit_log(booking_id, created_at DESC);

CREATE TABLE IF NOT EXISTS calendar_audit_log (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  calendar_event_id BIGINT NULL REFERENCES calendar_events(id) ON DELETE SET NULL,
  action          TEXT NOT NULL, -- 'create'|'update'|'delete'
  actor_type      TEXT NOT NULL DEFAULT 'admin',
  actor_id        UUID NULL,
  reason          TEXT NULL,
  meta            JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT calendar_audit_action_valid CHECK (action IN ('create','update','delete')),
  CONSTRAINT calendar_audit_actor_type_valid CHECK (actor_type IN ('user','admin','system'))
);

-- =========================================
-- Tokenized ICS links (read-only feeds)
-- =========================================
CREATE TABLE IF NOT EXISTS ics_tokens (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope         TEXT NOT NULL, -- 'locker'|'compartment'|'product'
  scope_id      BIGINT NOT NULL,
  token_hash    TEXT NOT NULL, -- store SHA-256 hex of the raw token
  label         TEXT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at    TIMESTAMPTZ NULL,

  CONSTRAINT ics_tokens_scope_valid CHECK (scope IN ('locker','compartment','product')),
  CONSTRAINT ics_tokens_token_hash_len CHECK (length(token_hash) >= 32)
);

CREATE UNIQUE INDEX IF NOT EXISTS ics_tokens_scope_scope_id_token_hash_uniq
  ON ics_tokens(scope, scope_id, token_hash);

COMMIT;
